spring.datasource.url=jdbc:postgresql://localhost:5432/libro_service
spring.datasource.username=postgres
spring.datasource.password=a

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
server.port=8081

# RabbitMQ Configuration
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# JWT Configuration (debe ser el mismo secret que auth-service)
jwt.secret=mySecretKeyForJWTTokenGenerationMustBeAtLeast256BitsLong12345678

# Actuator
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

